### ISSUE TITLE
How is this laptop?

### ISSUE THREAD

**Issue by amrit92** [W-Floyd/ASUS_K501UX-WH74#1]
Few questions:
How is the battery life with Linux? Can Graphics card be disabled?

**Comment by W-Floyd** [comment]
Battery life is not fantastic, but not horrible. I have yet to compare with Windows. Expect, _at most_, 4 hours doing office work, 1:30 gaming.

The GPU can be disabled. I installed bumblebee to allow selective use of the GPU. I followed [this](https://rajat-osgyan.blogspot.com/2016/04/how-to-install-latest-nvidia-drivers-on.html) guide. There are also instructions for nvidia prime, which requires logging out and back in again to switch, but likely provides better performance.

**Comment by amrit92** [comment]
Thanks for replying WIlliam. I am a developer who prefers using
Linux(Ubuntu/Arch). Would you recommend this laptop, or any alternative,
for the same specs/budget?

**Comment by W-Floyd** [comment]
Hmm. Well, this computer isn't without its issues. namely the fan. It seems to have a low temperature threshold to start, and has a fairly high rotation speed. Not an issue really, just something to consider. The fans also vent onto the bottom of the screen, which can be annoying, but that's just me.

Also, if you are dual booting windows (like I am - Edit: was), the 256 SSD can be a bit small. _It does have an empty drive bay though!_ I put a 512 SSD into the second bay, so general storage isn't an issue. Just another thing to keep in mind. No optical disk drive is fine for me, but your usage may vary.

It's not the most powerful machine out there for the price, but makes up for it in build quality in my opinion (Edit: Nope - [The more powerful, cheaper alternative](https://smile.amazon.com/Dell-15-6-Inch-Quad-Core-i5-6300HQ-Processor/dp/B015PYYDMQ/ref=sr_1_1?s=electronics&ie=UTF8&qid=1498433081&sr=1-1&keywords=Dell+Inspiron+i7559-763BLK) is of a better build quality). The matte screen is nice, and viewing angles are pretty good. The keyboard seems good to me, but I'm no typist. I do love the back lighting, especially at night.

The 4K screen is nice for general use (viewing documents, web browsing, etc.), but does come with some teething problems in software. That is no fault of the laptops, but should be kept in mind. Most software handle 4K fine, but some do not (GIMP icons are too small, same with Inkscape to some extent). If you decide on 4K as a developer, it would then be beneficial for the rest of us to have correctly scaling software. Edit: It should be noted that the laptop uses a staggered pixel layout (WRGB), so it's not a true 4K. Though this is common enough, it isn't desirable, and can be noticed up close.

Some games tend to have so-so performance (under Linux anyway). If it were just a Full HD screen, the GPU would be okay. But for heavy gaming on Linux, this is not the right machine. Again, no fault of the laptops, just something to consider.
One point I was impressed with was the range of brightness that the screen has. It can go _very_ low, which is great for nighttime use, and fairly high for daytime. IIRC there are over 900 brightness steps, which doesn't really help anything, but is neat anyway (on Windows it uses them for silky smooth brightness changes - Linux doesn't yet).

The amount of RAM is really nice. 16GB is more than I will regularly use right now, but I do need it now and again. The CPU is okay. In reality, a quad core i5 would be more powerful (edit: [about 50% more so](https://smile.amazon.com/Dell-15-6-Inch-Quad-Core-i5-6300HQ-Processor/dp/B015PYYDMQ/ref=sr_1_1?s=electronics&ie=UTF8&qid=1498433081&sr=1-1&keywords=Dell+Inspiron+i7559-763BLK)), but I am happy as it is.

Overall, I like it. Don't know what else I would recommend, it depends on your needs. If you want good quality more than performance, this is good. it isn't without its flaws, but overall pretty solid.

Edit: Yeah, not so much. I have become increasingly dissatisfied with the laptop over time. Ultimately, I've made my purchase, and will live with it, but in future, I would consider options differently.

Issues include (at the fault of the laptop):
* Mushy trackpad clicking
* Sub-par display quality, especially some weird, 'dynamic enhancement' type features, where I can see the whole colour balance of the screen shift when I click on GUI elements and they pop up colour quickly.
* Sub-par build quality. I can press on the area above the trackpad and the whole keyboard flexes in a little bit, even more so when I press above the keyboard. The bezel isn't that nice either.
* Loud, obnoxiously overactive fan.
* Small battery. 1 year in: 35.1/48.3 Wh (73%)

In future, I would:
* Go for 8GB RAM. I use 16GB because it's there, but I use an old Surface Pro 3 that has 4GB, and I do the same things in the end, just a bit differently.
* Go for a quad core i5 rather than an i7.
* **For all that is holy, get something with better battery life!**
* Not be so enamoured with a 'metal' body, and go for a solid plastic instead.
* Possibly go for a 14in or under. This is personal preference, but I'm seeing options out there with full GPUs that don't look huge either.

**Comment by amrit92** [comment]
Thanks a lot for the in depth review William. I am looking for similar specs
and build although i dont really need the graphics card. Maybe I will get
this.

**Comment by W-Floyd** [comment]
If the graphics card isn't an issue, then yes, it's a nice machine!
Feel free to ask any other questions.

Edit: It's just an okay machine, there were better options available at the time, and even more so now.

**Comment by amrit92** [comment]
So I can block the card and use the onboard one only?

**Comment by W-Floyd** [comment]
Absolutely. By default, I don't believe it will use it anyway (I may well be
wrong). If you install Nvidia Prime, that will allow complete switching from
Internal graphics to the dedicated GPU, which will require logging out and
back in again. If you install Bumblebee instead, you can run programs under
the GPU using another program.

**Comment by mneiger** [comment]
Hi guys,
I have a K501UX-DM050T, FHD, 128SSD, 1Tb HD, 8Gb upgraded to 12.
I'm very happy with this machine within the remarks Floyd made. The GPU is ok for me in FHD.
I transfered my never booting windows onto the HD and use it only with Linux Mint 18 xfce (upgraded from 17.3 this may bring its own issues).

Floyd, many thanks for your input, I'm glad to be able to use brightness now.
I'm having quite a few morenot critical  issues but for the one you're also facing with suspend : the nvidia GPU is not usable after resume.

Did you make progress on this last one?

**Comment by W-Floyd** [comment]
I'm glad I was able to help. As for the GPU, I believe it is an issue with the proprietary NVIDIA drivers, if I understand correctly. So no luck so far.

Edit: NVIDIA *may* have fixed this (the resume issues), but I have no way of testing at this point in time.

**Comment by mneiger** [comment]
Hi,

 does your k501 also suffer from spurious interrupts like this 
Aug 13 18:10:18 resh-lakish kernel: [ 1113.654825] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
Aug 13 18:10:18 resh-lakish kernel: [ 1113.654849] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
Aug 13 18:10:18 resh-lakish kernel: [ 1113.654860] pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00002000
Aug 13 18:10:18 resh-lakish kernel: [ 1113.654869] pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)

It's likely connected to wifi card and can be inhibited (but not solved) by adding pic=noaer on boot option.
cheers

**Comment by W-Floyd** [comment]
I'll admit, I don't know what you mean by spurious interrupts, and those
messages do not look familiar, but I have been experiencing problems with
my wifi card, so I shall try the suggested boot option and see if any
difference is made!

Edit: I see that the boot option suggested disables PCIE advanced error reporting. As I have yet to observe such errors, I shall leave things be.

**Comment by W-Floyd** [comment]
I'll close this now. Final remark for me is that the laptop is okay, but better choices may be made, especially in the time passed since I got it. Feel free to revisit this if it's somehow still relevant.
